### ISSUE TITLE
Compability with valheim-armorstand

### ISSUE THREAD

**Issue by torarnv** [PhantomGamers/Valheim-PreventAccidentalInteraction#2]
Thanks for a nice mod!

I tried enabling the interaction-block for the armour stand item provided by https://github.com/ceko/valheim-armorstand, but that resulted in neither of the items blocking interaction. 

I used the name `ArmorStand `, but I don't know if that is the right name. That seemed to be the class that has the `interact` method that this mod hooks.

Have you tried this mod, and whether it's possible to prevent interaction for the armour stand?

**Comment by PhantomGamers** [comment]
As it currently stands the mod is only compatible with objects that use a class from the base game. I will look into how I could possibly dynamically support classes added by other mods

**Comment by PhantomGamers** [comment]
Fixed in 1.0.4 dc80bc10fe440f12f70eb2a97aa68f19d2dd5587

You need to include the namespace when adding classes from other mods, so in this case, you would add `ValheimStands.Unity.ArmorStand`

There will be a warning in the log on startup but I don't know how to avoid it and to the best of my knowledge, it should have no adverse effect.

**Comment by torarnv** [comment]
Amazing, it works, thank you so much! :)
